// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tulajcsyfvgxvsdftikt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1bGFqY3N5ZnZneHZzZGZ0aWt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjM1MTIsImV4cCI6MjA2MDEzOTUxMn0.JJI-PQ4tjN7kwRsrukMbr6QjrN-_utbAjcN9DsEyzAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);